<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| File and Directory Modes
|--------------------------------------------------------------------------
|
| These prefs are used when checking and setting modes when working
| with the file system.  The defaults are fine on servers with proper
| security, but you may wish (or even need) to change the values in
| certain environments (Apache running a separate process for each
| user, PHP under CGI with Apache suEXEC, etc.).  Octal values should
| always be used to set the mode correctly.
|
*/
define('FILE_READ_MODE', 0644);
define('FILE_WRITE_MODE', 0666);
define('DIR_READ_MODE', 0755);
define('DIR_WRITE_MODE', 0777);

/*
|--------------------------------------------------------------------------
| File Stream Modes
|--------------------------------------------------------------------------
|
| These modes are used when working with fopen()/popen()
|
*/

define('FOPEN_READ',							'rb');
define('FOPEN_READ_WRITE',						'r+b');
define('FOPEN_WRITE_CREATE_DESTRUCTIVE',		'wb'); // truncates existing file data, use with care
define('FOPEN_READ_WRITE_CREATE_DESTRUCTIVE',	'w+b'); // truncates existing file data, use with care
define('FOPEN_WRITE_CREATE',					'ab');
define('FOPEN_READ_WRITE_CREATE',				'a+b');
define('FOPEN_WRITE_CREATE_STRICT',				'xb');
define('FOPEN_READ_WRITE_CREATE_STRICT',		'x+b');

/*
|--------------------------------------------------------------------------
| Base Urls
|--------------------------------------------------------------------------
|
|
*/

define('BASE_CSS', 'assets/css');
define('BASE_IMG', 'assets/img');
define('BASE_JS', 'assets/js');

/*
|--------------------------------------------------------------------------
| Constans Payments
|--------------------------------------------------------------------------
|
|
*/

define('SECOND_PAY', 'second_pay');
define('FIRST_PAY', 'first_pay');
define('ACCOUNT_PAY', 'account_pay');
define('COMPLETE_PAY', 'complete_pay');

/*
|--------------------------------------------------------------------------
| Extraordinary Constants
|--------------------------------------------------------------------------
|
|
*/

define('DIVIDE_COEFICCIENT', 0);
define('DIVIDE_EQUALS', 1);
define('DIVIDE_COEFICCIENT_LABEL', "Dividido por coeficiente");
define('DIVIDE_EQUALS_LABEL', "Dividido en partes iguales");

/*
|--------------------------------------------------------------------------
| Autogenerated pay days Constants
|--------------------------------------------------------------------------
|
|
*/

define ("WEEK_DAYS", serialize (array ("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday")));
define ("WEEK_DAYS_LABEL", serialize (array ("Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo")));
define ("MULTIPLICITY_AUTOGENERATED_DAYS", serialize (array ("each", "first", "second", "third", "fourth")));
define ("MULTIPLICITY_AUTOGENERATED_DAYS_LABEL", serialize (array ("Cada", "Primer", "Segundo", "Tercer", "Cuarto")));


/* End of file constants.php */
/* Location: ./application/config/constants.php */